// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDycMzccz_mbudrWXFXJYIaJWi4Xi3frxw',
    appId: '1:555750406282:web:dfc0dec607a5229d5d5573',
    messagingSenderId: '555750406282',
    projectId: 'elearningapp-4adde',
    authDomain: 'elearningapp-4adde.firebaseapp.com',
    databaseURL: 'https://elearningapp-4adde-default-rtdb.firebaseio.com',
    storageBucket: 'elearningapp-4adde.appspot.com',
    measurementId: 'G-F6627H164D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmMvWpHGeKxAHmX3u8kg1ut6Sq4hgGPdk',
    appId: '1:555750406282:android:3a6588989f8edddd5d5573',
    messagingSenderId: '555750406282',
    projectId: 'elearningapp-4adde',
    databaseURL: 'https://elearningapp-4adde-default-rtdb.firebaseio.com',
    storageBucket: 'elearningapp-4adde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3hI8LYVuMDQZfl-u3CqdgdGAmAgUPpuI',
    appId: '1:555750406282:ios:725a9c09c8f1726d5d5573',
    messagingSenderId: '555750406282',
    projectId: 'elearningapp-4adde',
    databaseURL: 'https://elearningapp-4adde-default-rtdb.firebaseio.com',
    storageBucket: 'elearningapp-4adde.appspot.com',
    iosBundleId: 'com.eLearningAdmin.eLearningAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3hI8LYVuMDQZfl-u3CqdgdGAmAgUPpuI',
    appId: '1:555750406282:ios:9fd748891625d86e5d5573',
    messagingSenderId: '555750406282',
    projectId: 'elearningapp-4adde',
    databaseURL: 'https://elearningapp-4adde-default-rtdb.firebaseio.com',
    storageBucket: 'elearningapp-4adde.appspot.com',
    iosBundleId: 'com.eLearningAdmin.eLearningAdmin.RunnerTests',
  );
}
